language: python
python:
  - 2.6
  - 2.7
  - 3.2
env:
  - DJANGO=1.5.8
  - DJANGO=1.6.5
before_install:
  - export DJANGO_SETTINGS_MODULE=custard.tests.settings
install:
  - pip install -q Django==$DJANGO
  - pip install coveralls
  - pip install .
matrix:
  exclude:
    # Django doesn't support following combinations
    - python: 2.6
      env: DJANGO=1.6.5
script:
  - coverage run --source=custard manage.py test custard
after_success:
  - coveralls
