language: python
python:
  - 2.7
  - 3.2
  - 3.3
  - 3.4
env:
  - DJANGO=1.6.7
  - DJANGO=1.7.0
before_install:
  - export DJANGO_SETTINGS_MODULE=custard.tests.settings
install:
  - pip install -q Django==$DJANGO
  - pip install coveralls
  - pip install .
script:
  - coverage run --timid --source=custard manage.py test custard
after_success:
  - coveralls
