language: python
python:
  - 2.7
env:
  - DJANGO=1.6.5
before_install:
  - export DJANGO_SETTINGS_MODULE=custard.tests.settings
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install . --use-mirrors
script:
  - python manage.py test custard
